/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.6.0.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as user_getIntro from "../user/getIntro";
import type * as user_storeUser from "../user/storeUser";
import type * as user_storeUsername from "../user/storeUsername";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  "user/getIntro": typeof user_getIntro;
  "user/storeUser": typeof user_storeUser;
  "user/storeUsername": typeof user_storeUsername;
}>;
