import Head from 'next/head'
import Image from 'next/image'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faBell, faVolumeHigh, faVolumeXmark, faBug } from '@fortawesome/free-solid-svg-icons'

export default function Home() {

  var buttons = [{ name: "Login" }, { name: "Create an Account" }]
  var iconsL = [
    { name: "Twitter", src: "/assets/icons/twitter.svg" },
    { name: "Discord", src: "/assets/icons/discord.svg" },
    { name: "Fandom", src: "/assets/icons/fandom.svg" },
  ]
  var iconsR = [
    { name: "Notifications", src: faBell },
    { name: "Volume", src: faVolumeHigh },
    { name: "Bug Report", src: faBug },
  ]

  return (
    <div>
      <Head>
        <title>Journeyer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex flex-col justify-center">
        <div className="flex justify-center mb-20">
          <p className="text-7xl font-bold text-center drop-shadow-md">JOURNEYER<br />
            <span className="text-4xl">OF THE REALMS</span>
          </p>
        </div>
        <div className="grid grid-rows-2 gap-2 justify-center mb-20">
          {buttons.map((button, index) => {
            return (
              <button key={index} className="btn-primary text-lg rounded-sm drop-shadow-md py-3 w-56">
                {button.name}
              </button>
            )
          })}
        </div>
      </main>
      <footer className="fixed bottom-0 w-full">
        <div className="grid grid-cols-2">
          <div className="grid grid-flow-col auto-cols-max">
            {iconsL.map((icon, index) => {
              return (
                <div key={index} className="flex justify-center pl-6 pr-3 pb-4">
                  <Image
                    src={icon.src}
                    width={24}
                    height={24}
                    alt={icon.name}
                  />
                </div>
              )
            })}
          </div>
          <div className="grid grid-flow-col col-start-13 auto-cols-max">
            {iconsR.map((icon, index) => {
              return (
                <div key={index} className="flex justify-center pl-3 pr-6 pb-4">
                  <FontAwesomeIcon
                    alt={icon.name}
                    icon={icon.src}
                    style={{ fontSize: 24, color: "rgb(20 184 166)" }}
                  />
                </div>
              )
            })}
          </div>
        </div>
      </footer>
    </div>
  )
}
