import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
            <h1>Hello Next.js</h1>
            <p>
                <Image src="/vercel.svg" alt="Next.js" width={300} height={300} />
            </p>
        </main>
    </div>
  )
}
